packages:
    - "examples/**/*"
    - "packages/**/*"
    - "!**/.next/**"
    - "!**/dist/**"

catalog:
    viem: 2.21.49
    zod: 3.23.8
    "@solana/web3.js": 1.95.8
    ai: 4.0.3
    "@langchain/core": 0.3.6
